# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1030)
        MainWindow.setStyleSheet("background-color: rgb(5, 0, 5)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(520, 40, 1371, 951))
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 110, 481, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Slider_ft = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Slider_ft.setMinimum(1)
        self.Slider_ft.setMaximum(100)
        self.Slider_ft.setSingleStep(1)
        self.Slider_ft.setProperty("value", 18)
        self.Slider_ft.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_ft.setObjectName("Slider_ft")
        self.gridLayout.addWidget(self.Slider_ft, 2, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 7, 1, 1)
        self.Slider_Step = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Slider_Step.setMinimum(1)
        self.Slider_Step.setMaximum(1000)
        self.Slider_Step.setPageStep(10)
        self.Slider_Step.setProperty("value", 199)
        self.Slider_Step.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Step.setObjectName("Slider_Step")
        self.gridLayout.addWidget(self.Slider_Step, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 1)
        self.EmEdit_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EmEdit_3.setFont(font)
        self.EmEdit_3.setStyleSheet("color: yellow")
        self.EmEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.EmEdit_3.setObjectName("EmEdit_3")
        self.gridLayout.addWidget(self.EmEdit_3, 0, 6, 1, 1)
        self.step = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.step.setFont(font)
        self.step.setStyleSheet("color: rgb(218, 98, 0)")
        self.step.setAlignment(QtCore.Qt.AlignCenter)
        self.step.setObjectName("step")
        self.gridLayout.addWidget(self.step, 1, 2, 1, 1)
        self.Slider_t0 = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Slider_t0.setMinimum(0)
        self.Slider_t0.setMaximum(100)
        self.Slider_t0.setProperty("value", 0)
        self.Slider_t0.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_t0.setObjectName("Slider_t0")
        self.gridLayout.addWidget(self.Slider_t0, 2, 4, 1, 1)
        self.precision = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.precision.setFont(font)
        self.precision.setStyleSheet("color: rgb(218, 98, 0)")
        self.precision.setAlignment(QtCore.Qt.AlignCenter)
        self.precision.setObjectName("precision")
        self.gridLayout.addWidget(self.precision, 1, 0, 1, 1)
        self.LEdit_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LEdit_2.setFont(font)
        self.LEdit_2.setStyleSheet("color:yellow")
        self.LEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.LEdit_2.setObjectName("LEdit_2")
        self.gridLayout.addWidget(self.LEdit_2, 0, 2, 1, 1)
        self.EmEdit_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EmEdit_2.setFont(font)
        self.EmEdit_2.setStyleSheet("color: yellow")
        self.EmEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.EmEdit_2.setObjectName("EmEdit_2")
        self.gridLayout.addWidget(self.EmEdit_2, 0, 4, 1, 1)
        self.t0 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.t0.setFont(font)
        self.t0.setStyleSheet("color: rgb(218, 98, 0)")
        self.t0.setAlignment(QtCore.Qt.AlignCenter)
        self.t0.setObjectName("t0")
        self.gridLayout.addWidget(self.t0, 1, 4, 1, 1)
        self.Slider_Precision = QtWidgets.QSlider(self.gridLayoutWidget)
        self.Slider_Precision.setMinimum(1)
        self.Slider_Precision.setMaximum(20)
        self.Slider_Precision.setProperty("value", 17)
        self.Slider_Precision.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Precision.setObjectName("Slider_Precision")
        self.gridLayout.addWidget(self.Slider_Precision, 2, 0, 1, 1)
        self.RLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.RLabel.setFont(font)
        self.RLabel.setStyleSheet("color: yellow")
        self.RLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RLabel.setObjectName("RLabel")
        self.gridLayout.addWidget(self.RLabel, 0, 0, 1, 1)
        self.ft = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ft.setFont(font)
        self.ft.setStyleSheet("color: rgb(218, 98, 0)")
        self.ft.setAlignment(QtCore.Qt.AlignCenter)
        self.ft.setObjectName("ft")
        self.gridLayout.addWidget(self.ft, 1, 6, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 380, 471, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:rgb(29, 29, 29);\n"
"color: yellow")
        self.pushButton.setObjectName("pushButton")
        self.RLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.RLabel_2.setGeometry(QtCore.QRect(40, 40, 175, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.RLabel_2.setFont(font)
        self.RLabel_2.setStyleSheet("color: yellow")
        self.RLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.RLabel_2.setObjectName("RLabel_2")
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(230, 40, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.time.setFont(font)
        self.time.setStyleSheet("color:  rgb(218, 98, 0)")
        self.time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time.setObjectName("time")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.EmEdit_3.setText(_translate("MainWindow", "ft"))
        self.step.setText(_translate("MainWindow", "10"))
        self.precision.setText(_translate("MainWindow", "1"))
        self.LEdit_2.setText(_translate("MainWindow", "Шаг"))
        self.EmEdit_2.setText(_translate("MainWindow", "t0"))
        self.t0.setText(_translate("MainWindow", "1"))
        self.RLabel.setText(_translate("MainWindow", "Порядок точности"))
        self.ft.setText(_translate("MainWindow", "0.05"))
        self.pushButton.setText(_translate("MainWindow", "Моделировать"))
        self.RLabel_2.setText(_translate("MainWindow", "Время"))
        self.time.setText(_translate("MainWindow", "0"))
